spring:
  datasource:
    url: jdbc:h2:mem:bookstore_prd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enable: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  logging:
    level:
      br:
        com:
          zrtech: INFO